<def f='llvm/llvm/include/llvm/Support/Error.h' l='198' ll='201' type='void llvm::Error::Error(std::unique_ptr&lt;ErrorInfoBase&gt; Payload)'/>
<use f='llvm/llvm/include/llvm/Support/Error.h' l='413' u='c' c='_ZN4llvm9ErrorList4joinENS_5ErrorES1_'/>
<use f='llvm/llvm/include/llvm/Support/Error.h' l='861' u='c' c='_ZN4llvm15handleErrorImplESt10unique_ptrINS_13ErrorInfoBaseESt14default_deleteIS1_EE'/>
<use f='llvm/llvm/include/llvm/Support/Error.h' l='1191' u='c' c='_ZN4llvm9FileError9takeErrorEv'/>
<use f='llvm/llvm/include/llvm/Support/Error.h' l='1210' u='c' c='_ZN4llvm9FileError5buildERKNS_5TwineENS_8OptionalImEENS_5ErrorE'/>
<use f='llvm/llvm/include/llvm/Support/Error.h' l='1301' u='c' c='_ZN4llvm6unwrapEP15LLVMOpaqueError'/>
<doc f='llvm/llvm/include/llvm/Support/Error.h' l='196'>/// Create an error value. Prefer using the &apos;make_error&apos; function, but
  /// this constructor can be useful when &quot;re-throwing&quot; errors from handlers.</doc>
<use f='llvm/llvm/lib/Object/Error.cpp' l='91' u='c' c='_ZN4llvm6object31isNotObjectErrorInvalidFileTypeENS_5ErrorE'/>
<use f='llvm/llvm/lib/ProfileData/InstrProfReader.cpp' l='699' u='c' c='_ZN4llvm30InstrProfReaderItaniumRemapper10getRecordsENS_9StringRefERNS_8ArrayRefINS_20NamedInstrProfRecordEEE'/>
<use f='llvm/llvm/lib/Support/Error.cpp' l='90' u='c' c='_ZN4llvm16errorCodeToErrorESt10error_code'/>
<use f='llvm/llvm/tools/llvm-profdata/llvm-profdata.cpp' l='101' u='c' c='_ZL22handleMergeWriterErrorN4llvm5ErrorENS_9StringRefES1_b'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/RemoteObjectLayer.h' l='185' u='c' c='_ZN4llvm3orc17RemoteObjectLayer6teeLogENS_5ErrorE'/>
<use f='llvm/llvm/unittests/Support/ErrorTest.cpp' l='407' u='c' c='_ZN12_GLOBAL__N_129Error_FailureFromHandler_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/ErrorTest.cpp' l='424' u='c' c='_ZN12_GLOBAL__N_132Error_CatchErrorFromHandler_Test8TestBodyEv'/>
